
var precios,dolarven,fecha,datos,criptoBTC,criptoETH,criptoBCH,criptoLTC;var directorio='/Latin-markets-calculator/imagenes/';var logos=['btc.svg','eth.svg','bch.svg','ltc.svg'];var Banderas=['ars.svg','bob.svg','brl.svg','clp.svg','cop.svg','crc.svg','dop.svg','mxn.svg','pab.svg','pen.svg','pyg.svg','uyu.svg','ves.svg','usd.svg','eur.svg'];var cod_moneda=['ARS','BOB','BRL','CLP','COP','CRC','DOP','MXN','PAB','PEN','PYG','UYU','VES','USD','EUR'];var cod_cripto=['BTC','ETH','BCH','LTC'];function cambiarcripto(codigo){var codigo=parseInt(codigo.substring(0,1));var indice=document.getElementById('indice').value;document.getElementById('banderaA').src=URLactual.concat(directorio,logos[codigo]);document.getElementById('codigoA').innerHTML=cod_cripto[codigo];document.getElementById('monedaB').value=precios[indice];switch(codigo){case 0:precios=criptoBTC;break;case 1:precios=criptoETH;break;case 2:precios=criptoBCH;break;case 3:precios=criptoLTC;break};calcular('monedaA','monedaB',indice,"m");var b2=precios[indice]/document.getElementById('monedaA').value;var b3=cod_moneda[indice];var cambiotipo=' 1 '.concat(cod_cripto[codigo],' = ');tipo_cambio('tipo',cod_cripto[codigo],b3,b2)}
function cambiarmoneda(valor){var URLbandera=URLactual.concat(directorio,Banderas[valor]);calcular('monedaA','monedaB',valor,"m");document.getElementById('indice').value=valor;document.getElementById('banderaB').src=URLbandera;document.getElementById('codigoB').innerHTML=cod_moneda[valor];var b1=document.getElementById('codigoA').innerHTML;tipo_cambio('tipo',b1,cod_moneda[valor],precios[valor])}
function cambiamonedaA(){calcular('monedaA','monedaB',document.getElementById('indice').value,"m")}
function cambiamonedaB(){calcular('monedaB','monedaA',document.getElementById('indice').value,"d")}
function calcular(origen,destino,indice,operacion){let resultado=0;let calculo=0;let campo;let operando=document.getElementById(origen).value;if(operando){operando=operando.replace(/\./g,'').replace(/,/g,'.');campo=parseFloat(operando);if(operacion=="m"){calculo=campo*precios[indice];resultado=calculo.format(2,3,'.',',')}else if(operacion=="d"){if(precios[indice]!=0){calculo=campo/precios[indice];resultado=calculo.format(8,3,'.',',')}}}else{resultado=calculo.format(2,3,'.',',')}
document.getElementById(destino).value=resultado}
function tipo_cambio(target,codigo_cripto,codigo_moneda,monto_moneda){document.getElementById(target).innerHTML=' 1 '.concat(codigo_cripto,' = ').concat(new Intl.NumberFormat('es-ES',{style:'currency',currency:codigo_moneda,currencyDisplay:'code'}).format(monto_moneda))}
Number.prototype.format=function(n,x,s,c){var re='\\d(?=(\\d{'+(x||3)+'})+'+(n>0?'\\D':'$')+')',num=this.toFixed(Math.max(0,~~n));return(c?num.replace('.',c):num).replace(new RegExp(re,'g'),'$&'+(s||','))}
